version: 2

project_name: toshiki-avatar

before:
  hooks:
    - go mod tidy

builds:
  # Linux amd64 with CGO enabled (WebP support)
  - id: toshiki-avatar-linux-amd64
    main: ./main.go
    binary: toshiki-avatar
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
    flags:
      - -trimpath
    ldflags:
      - -s -w

  # Linux arm64 without CGO (pure Go, PNG/JPEG only)
  - id: toshiki-avatar-linux-arm64
    main: ./main.go
    binary: toshiki-avatar
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w

  # macOS Intel + Apple Silicon (pure Go)
  - id: toshiki-avatar-darwin
    main: ./main.go
    binary: toshiki-avatar
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - id: default
    builds:
      - toshiki-avatar-linux-amd64
      - toshiki-avatar-linux-arm64
      - toshiki-avatar-darwin
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}-
      {{- lower .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

    files:
      - README.md
      - LICENSE
      - "avatars/*"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'

release:
  github:
    owner: andatoshiki
    name: toshiki-avatar
