version: 2

project_name: toshiki-avatar

builds:
  - id: toshiki-avatar
    main: ./main.go
    binary: toshiki-avatar
    goos:
      - linux
      - darwin
      - windows
      - freebsd
      - openbsd
      - netbsd
      - dragonfly
      - solaris
    goarch:
      - amd64
      - arm64
      - 386
      - arm
      - ppc64le
      - s390x
      - riscv64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/andatoshiki/toshiki-avatar/internal.Version={{.Version}}

archives:
  - id: default
    builds:
      - toshiki-avatar
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}-v{{ .Arm }}{{ end }}'
    files:
      - README.md
      - LICENSE
      - "avatars/*"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'

release:
  github:
    owner: andatoshiki
    name: toshiki-avatar
