version: 2

project_name: toshiki-avatar

before:
  hooks:
    - go mod tidy

builds:
  - id: toshiki-avatar
    main: ./main.go
    binary: toshiki-avatar
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - id: default
    builds:
      - toshiki-avatar
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}-
      {{- lower .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

    files:
      - README.md
      - LICENSE
      - "avatars/*"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'

release:
  github:
    owner: andatoshiki
    name: toshiki-avatar
